name: Backend CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run backend tests with coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt
          pip install flake8 pytest-cov  # Install pytest-cov for coverage

      - name: Run backend tests with coverage
        run: |
          source venv/bin/activate
          pytest --cov=backend --cov-report=xml --cov-report=term-missing -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml  # Uploads the coverage report as an artifact

      - name: Lint backend code
        run: |
          source venv/bin/activate
          flake8 backend/
