name: Backend CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt
          pip install flake8  # Install flake8 explicitly

      - name: Setup SQLite database (if needed)
        run: |
          source venv/bin/activate
          python backend/manage.py db upgrade  # Adjust if using Flask-Migrate

      - name: Run backend tests
        run: |
          source venv/bin/activate
          python -m pytest --maxfail=1 --disable-warnings -v

      - name: Lint backend code
        run: |
          source venv/bin/activate
          flake8 backend/

